### ISSUE TITLE
PDF Schematics for documetation

### ISSUE THREAD

**Issue by ngkr** [Fabien-Chouteau/picoprobe-pcb#1]
Please add a pdf version of the schematics. I know it is simple, but it would save some pain installing Eagle just to have a look :-)

**Comment by Fabien-Chouteau** [comment]
Here you go: https://github.com/Fabien-Chouteau/picoprobe-pcb/blob/main/production/rev-1.0/PicoProbePCB-rev-1.0-schematics.pdf

BTW, the board is designed with Kicad, not Eagle ;)

Cheers

**Comment by ngkr** [comment]
Thanks a lot!
